language: php
php:
  - 5.6
  - 7.0
  - hhvm

env:
  - PHP_BIN=php

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/tester -p $PHP_BIN test/test.php

sudo: false